### ISSUE TITLE
ts-error: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by emi2k01** [jotaijs/jotai-optics#9]
```ts
const stateAtom = atom({
  a: 0,
});

export const aAtom = focusAtom(stateAtom, (optic) => optic.prop("a"));
                  // ^^ Type instantiation is excessively deep and possibly infinite

```

Can be fixed as described here: https://github.com/jotaijs/jotai-optics/issues/6#issuecomment-1586383089 but I'm not sure of the implications.

Typescript: v5.1.3

**Comment by dai-shi** [comment]
Thanks for reporting! A PR would be helpful. I'm not sure about the implication either.
(btw, we look for a maintainer for this package.)

**Comment by emi2k01** [comment]
I stopped using this package since I realized it doesn't really prevents re-renders when splitting a large object.

Right now, doing `atom(get => get(stateAtom).prop, (get, set) => ...)` manually seems to work as well without having to include optics-ts

I think the docs should be updated.

https://jotai.org/docs/recipes/large-objects

> If we change the films property of the above data example, the peopleAtom won't cause a re-render

This is not true.

I think adapting this comment to be included in the docs should be better: https://github.com/pmndrs/jotai/issues/255#issuecomment-759447615

What do you think?

**Comment by dai-shi** [comment]
> Right now, doing `atom(get => get(stateAtom).prop, (get, set) => ...)` manually seems to work as well without having to include optics-ts

That's correct. I don't think we need optics-ts if our needs is just `.prop`.

> Maybe worth it to open an issue on the main jotai repo?

Please feel free to open a PR to improve docs directly in the jotai repo. If you want to discuss in advance, you can open a discussion.

**Comment by JamieKudla** [comment]
> That's correct. I don't think we need optics-ts if our needs is just `.prop`.

For the example above, how would you make a derived read/write atom without `focusAtom`?

```
const stateAtom = atom({
  a: 0,
});

// via focusAtom
export const aAtom = focusAtom(stateAtom, (optic) => optic.prop("a"));

// without focusAtom
export const aAtom = atom((get) => get(stateAtom).a, (get, set) => ???)
```

**Comment by dai-shi** [comment]
```js
const stateAtom = atom({
  a: 0,
});

// via focusAtom
export const aAtom = focusAtom(stateAtom, (optic) => optic.prop("a"));

// without focusAtom
export const aAtom = atom(
  (get) => get(stateAtom).a,
  (get, set, val) => set(stateAtom, (prev) => ({ ...prev, a: val }))
);
```
